! Configuration File for keepalived

global_defs {
  notification_email {
    acassen@firewall.loc
    failover@firewall.loc
    sysadmin@firewall.loc
  }
  notification_email_from Alexandre.Cassen@firewall.loc
  smtp_server 127.0.0.1
  smtp_connect_timeout 30
  router_id {{ ansible_fqdn }}
  vrrp_skip_check_adv_addr
  vrrp_garp_interval 0
  vrrp_gna_interval 0
  # 禁用vrrp_strict，允许vip可以被ping通。
  # vrrp_strict
}

vrrp_script check_nginx_pid {
  script "/usr/sbin/pidof nginx"
  interval 3
  weight -10
  fall 3
  rise 2
  user root
}

vrrp_instance VI_1 {
  state {{ vrrp_master_state }}
  interface ens192
  virtual_router_id {{ vrrp_instance1_id | default("51") }}   # 这个值在Master和Backup服务器上必须相同，以确保它们属于同一个VRRP实例。
  priority {{ vrrp_master_priority }}
  advert_int 1
  
  authentication {
      auth_type PASS
      auth_pass {{ vrrp_master_auth_pass | default("1111") }}
  }
  
  virtual_ipaddress {
      {{ vrrp_master_ip | default("192.168.0.1") }}
  }
  
  track_script {
    check_nginx_pid
  }
}

vrrp_instance VI_2 {
  state {{ vrrp_backup_state }}
  interface ens192
  virtual_router_id {{ vrrp_instance2_id | default("52") }}
  priority {{ vrrp_backup_priority }}
  advert_int 1
  
  authentication {
      auth_type PASS
      auth_pass {{ vrrp_backup_auth_pass | default("1111") }}
  }
  
  virtual_ipaddress {
      {{ vrrp_backup_ip | default("192.168.0.2") }}
  }
  
  track_script {
    check_nginx_pid
  }
}
