---
- name: download package
  unarchive:
    src: "{{ pkg }}"
    dest: /usr/local
    remote_src: yes

- name: configure loki
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: '[['
    variable_end_string: ']]'
  with_items:
    - { src: "values.yaml", dest: "/usr/local/loki/values.yaml" }

- name: install loki
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm uninstall --namespace {{ namespace }} loki
    helm install --values values.yaml --create-namespace --namespace {{ namespace }} loki .
  args:
    chdir: "/usr/local/loki"
  ignore_errors: yes
  register: install_loki

- name: show install loki log
  debug:
    msg:
      - "{{ install_loki.stdout_lines }}"
      - "{{ install_loki.stderr_lines }}"