haproxy:
  - job_name: "haproxy"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "haproxy"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/haproxy.log*
