nginx_harbor:
  - job_name: "nginx-harbor-access"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "harbor-access"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/harbor.idc.{{ wan_domain }}.log*

  - job_name: "nginx-harbor-error"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "harbor-error"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/harbor.idc.{{ wan_domain }}.err*
