nginx_grafana:
  - job_name: "nginx-grafana-access"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "grafana-access"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/grafana.idc.{{ wan_domain }}.log*

  - job_name: "nginx-grafana-error"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "grafana-error"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/grafana.idc.{{ wan_domain }}.err*
