nginx_zabbix:
  - job_name: "nginx-zabbix-access"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "zabbix-access"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/zabbix.idc.{{ wan_domain }}.log*

  - job_name: "nginx-zabbix-error"
    static_configs:
      - targets:
          - localhost
        labels:
          app: "nginx"
          type: "zabbix-error"
          ip: "{{ ansible_default_ipv4.address }}"
          hostname: "{{ ansible_fqdn }}"
          __path__: /var/log/nginx/zabbix.idc.{{ wan_domain }}.err*
