---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: roywong-work-letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: whh881114@gmail.com
    privateKeySecretRef:
      name: roywong-work-letsencrypt
    solvers:
      - selector:
          dnsZones:
            - '*.idc.roywong.work'
            - '*.idc-ingress-nginx-lan.roywong.work'
            - '*.idc-ingress-nginx-wan.roywong.work'
            - '*.idc-istio-gateway-lan.roywong.work'
            - '*.idc-istio-gateway-wan.roywong.work'
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret