---
- name: download package
  unarchive:
    src: "{{ pkg }}"
    dest: "{{ pkg_download_dir }}"
    remote_src: yes

- name: configure thanos
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: '[['
    variable_end_string: ']]'
  with_items:
    - { src: "values.yaml", dest: "{{ pkg_root_dir }}/values.yaml" }

- name: install thanos
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm uninstall thanos --namespace {{ prometheus_namespace }}
    helm install --values values.yaml --create-namespace --namespace {{ prometheus_namespace }} thanos .
  args:
    chdir: "{{ pkg_root_dir }}"
  ignore_errors: yes
  register: install_thanos

- name: install thanos log
  debug:
    msg:
      - "{{ install_thanos.stdout_lines }}"
      - "{{ install_thanos.stderr_lines }}"

