---
- name: tune system
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  with_items:
    - { name: "net.ipv4.ip_forward",                  value: "1" }
    - { name: "net.bridge.bridge-nf-call-iptables",   value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables",  value: "1" }
