---
- name: tune system
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.conf
  with_items:
    #  增加文件描述符限制：确保系统可以处理大量的文件描述符（每个连接需要一个文件描述符）。
    - { name: "fs.file-max",                  value: "1000000" }

    # 调整网络参数：优化 TCP/IP 栈以处理高并发连接。
    - { name: "net.ipv4.tcp_mem",             value: "786432 1697152 1945728" }
    - { name: "net.ipv4.tcp_rmem",            value: "4096 4096 16777216" }
    - { name: "net.ipv4.tcp_wmem",            value: "4096 4096 16777216" }
    - { name: "net.core.somaxconn",           value: "65535" }
    - { name: "net.core.netdev_max_backlog",  value: "50000" }
    - { name: "net.core.rmem_max",            value: "16777216" }
    - { name: "net.core.wmem_max",            value: "16777216" }
    - { name: "net.ipv4.tcp_rmem",            value: "4096 87380 16777216" }
    - { name: "net.ipv4.tcp_wmem",            value: "4096 65536 16777216" }
    - { name: "net.ipv4.tcp_mem",             value: "16777216 16777216 16777216" }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: "4096" }
    - { name: "net.ipv4.tcp_sack",            value: "1" }
    - { name: "net.ipv4.tcp_window_scaling",  value: "1" }
    - { name: "net.ipv4.tcp_fin_timeout",     value: "30" }
    - { name: "net.ipv4.tcp_keepalive_time",  value: "600" }
    - { name: "net.ipv4.ip_local_port_range", value: "1024 65535" }

    # 调整TCP连接跟踪表大小：提高系统对大量连接的处理能力。
    - { name: "net.ipv4.ip_local_port_range",                       value: "1024 65535" }
    - { name: "net.netfilter.nf_conntrack_max",                     value: "1000000" }
    - { name: "net.netfilter.nf_conntrack_tcp_timeout_established", value: "86400" }
    - { name: "net.netfilter.nf_conntrack_tcp_timeout_time_wait",   value: "30" }

    # 调优内存参数：确保系统有足够的内存用于网络缓存。
    - { name: "vm.min_free_kbytes",   value: "65536" }