---
- name: generate main config file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ group }}"
    mode: "0644"
  with_items:
    - { src: master/named.conf.j2, dest: /etc/named.conf }
    - { src: master/named.rfc1912.zones.j2, dest: /etc/named.rfc1912.zones }
  notify: restart-bind

- name: generate rfc1912 zone files
  template:
    src:  "master/{{ item }}.zone.j2"
    dest: "{{ master_zone_dir}}/{{ item }}.zone"
    group: "{{ group }}"
    mode: "0644"
  with_items: "{{ zones }}"
  notify: restart-bind

- name: generate rfc1912 reversed zone files
  template:
    src:  "master/{{ item.domain_name }}.rev.zone.j2"
    dest: "{{ master_zone_dir}}/{{ item.domain_name }}.rev.zone"
    group: "{{ group }}"
    mode: "0644"
  with_items: "{{ rev_zones }}"
  notify: restart-bind