---
- name: download package
  unarchive:
    src: "{{ godaddy_pkg }}"
    dest: /usr/local
    remote_src: yes

- name: configure cert-manager
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: '[['
    variable_end_string: ']]'
  with_items:
    - { src: "values_godaddy_webhook.yaml", dest: "/usr/local/godaddy-webhook/values.yaml" }

- name: install cert-manager
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm uninstall godaddy-webhook --namespace {{ namespace }}
    helm install --values values.yaml --create-namespace --namespace {{ namespace }} godaddy-webhook .
  args:
    chdir: "/usr/local/godaddy-webhook"
  ignore_errors: yes
  register: install_godaddy_webhook

- name: show install godaddy-webhook log
  debug:
    msg:
      - "{{ install_godaddy_webhook.stdout_lines }}"
      - "{{ install_godaddy_webhook.stderr_lines }}"
