---
- name: download package
  unarchive:
    src: "{{ pkg }}"
    dest: /usr/local
    remote_src: yes

- name: configure cert-manager
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: '[['
    variable_end_string: ']]'
  with_items:
    - { src: "values.yaml", dest: "/usr/local/cert-manager/values.yaml" }

- name: install crds
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    wget "{{ item }}" -O tmp.yaml
    kubectl delete -f tmp.yaml
    kubectl apply -f tmp.yaml
    rm -f tmp.yaml
  with_items:
    - "{{ crds_files }}"


- name: install cert-manager
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm uninstall cert-manager --namespace {{ namespace }}
    helm install --values values.yaml --create-namespace --namespace {{ namespace }} cert-manager .
  args:
    chdir: "/usr/local/cert-manager"
  ignore_errors: yes
  register: install_cert_manager

- name: show install cert-manager log
  debug:
    msg:
      - "{{ install_cert_manager.stdout_lines }}"
      - "{{ install_cert_manager.stderr_lines }}"
