---
- name: download package
  unarchive:
    src: "ftp://central-server.freedom.org/istio/istiod-{{ version }}.tgz"
    dest: "{{ istio_dir }}"
    remote_src: yes

- name: configure istiod
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    variable_start_string: '[['
    variable_end_string: ']]'
  with_items:
    - { src: "values_istiod.yaml", dest: "{{ istio_dir }}/istiod/values.yaml" }

- name: install ingress-nginx
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm install --values values.yaml --create-namespace --namespace {{ namespace }} istiod .
  args:
    chdir: "{{ istio_dir }}/istiod"
  ignore_errors: yes
  register: install_log

- name: show install log
  debug:
    msg:
      - "{{ install_log.stdout_lines }}"
      - "{{ install_log.stderr_lines }}"
