---
- name: uninstall istio
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    helm delete istio-ingress -n istio-ingress
    helm delete istiod -n {{ namespace }}
    helm delete istio-base -n {{ namespace }}
  ignore_errors: yes
  register: uninstall

- name: show uninstall log
  debug:
    msg:
      - "{{ uninstall.stdout_lines }}"
      - "{{ uninstall.stderr_lines }}"
