---
- name: download image
  shell: |
    docker pull "{{ mirror_registry }}/{{ item }}"
    docker tag  "{{ mirror_registry }}/{{ item }}" "{{ registry }}/{{ item }}"
    docker push "{{ registry }}/{{ item }}"
  loop:
    - registry.k8s.io/autoscaling/addon-resizer:1.8.20
    - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.13.0
    - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2
    - registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.1
    - registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
    - registry.k8s.io/kube-apiserver:v1.30.3
    - registry.k8s.io/kube-controller-manager:v1.30.3
    - registry.k8s.io/kube-scheduler:v1.30.3
    - registry.k8s.io/kube-proxy:v1.30.3
    - registry.k8s.io/coredns/coredns:v1.11.1
    - registry.k8s.io/pause:3.9
    - registry.k8s.io/etcd:3.5.12-0
    - registry.k8s.io/ingress-nginx/controller:v1.11.1
    - registry.k8s.io/ingress-nginx/controller:v1.12.1
    - registry.k8s.io/ingress-nginx/opentelemetry:v20230721-3e2062ee5
    - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.1
    - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.5.0
    - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20221220-controller-v1.5.1-58-g787ea74b6
    - registry.k8s.io/defaultbackend-amd64:1.5
    #- registry.k8s.io/metrics-server/metrics-server:0.7.1
  ignore_errors: yes
