---
- name: kubernetes master
  hosts:
    - 10.255.1.12
    - 10.255.1.22
    - 10.255.1.23
  user: root
  roles:
    - role: consul
      tags:
        - consul
      vars:
        services:
          - name: kubernetes-master
            port: 6443
          - name: kubernetes-apiserver
            port: 6443
          # istio-ingress-gateway nodeport
          - name: ingress-istio-status-nodeport
            port: 30021
          - name: ingress-istio-http-nodeport
            port: 30080
          - name: ingress-istio-https-nodeport
            port: 30443
          # ingress-nginx-nginx nodeport
          - name: ingress-nginx-http-nodeport
            port: 31080
          - name: ingress-nginx-https-nodeport
            port: 31443
