---
- name: Initialize the host by the playbook
  hosts:
    - 10.255.0.252
    - 10.255.1.6
    - 10.255.1.7
    - 10.255.1.8
  user: root
  roles:
    - role: common
      tags:
        - common

    - role: zabbix-agent2
      tags:
        - zabbix
        - zabbix-agent
        - zabbix-agent2

    - role: consul
      tags:
        - consul
      vars:
        services:
          - name: minio-s3
            port: 9000
          - name: minio-console
            port: 9001

    - role: minio
      tags:
        - minio
        - cos

    - role: promtail
      tags:
        - promtail
