---
- name: Initialize the host by the playbook
  hosts: 10.255.1.13
  user: root
  roles:
    - role: common
      tags:
        - common

    - role: zabbix-agent2
      tags:
        - zabbix
        - zabbix-agent
        - zabbix-agent2

    - role: consul
      tags:
        - consul
      vars:
        services:
          - name: zabbix-server
            port: 10051

    - role: promtail
      tags:
        - promtail
      vars:
        scrape_projects:
          - mysqld
          - zabbix_server

    - role: mysqld-exporter
      tags:
        - mysqld-exporter