---
- include: roles/common/handlers/main.yml

- name: restart-NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes

- name: restart-haproxy
  service:
    name: haproxy
    state: restarted
    enabled: yes

- name: reload-haproxy
  service:
    name: haproxy
    state: reloaded
    enabled: yes