---
- name: install packages
  yum:
    name: "{{ pkgs }}"
    state: present
    disable_gpg_check: yes

- name: configure loki
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: config.yml, dest: /etc/loki/config.yml }
  notify:
    - systemctl-daemon-reload
    - restart-loki
