---
- name: install packages
  yum:
    name: "{{ pkgs }}"
    state: present
    disable_gpg_check: yes

- name: create group
  group:
    name: "{{ group }}"
    system: yes
    state: present

- name: creat user
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    system: yes
    create_home: no
    state: present
    shell: /sbin/nologin

- name: chown minio data directories
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ group }}"
  loop: "{{ minio_data_dirs }}"

- name: configure minio
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: minio, dest: /etc/default/minio }
    - { src: minio.service.j2, dest: /usr/lib/systemd/system/minio.service }
  notify:
    - systemctl-daemon-reload
    - restart-minio